name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package -Dmaven.test.skip=true

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          GOOGLE_CALENDAR_APIKEY: ${{ secrets.GOOGLE_CALENDAR_APIKEY }}
        run: |
          echo "Deploying to Fly.io..."
          fly deploy --config fly.toml --dockerfile Dockerfile --build-arg GOOGLE_CALENDAR_APIKEY=$GOOGLE_CALENDAR_APIKEY
